export const groups=['identity','appearance','outfit','expression','pose','gaze','prop','action'] as const;
export type Group=typeof groups[number];
export const labels:Record<Group,string>={identity:'이름 / 작품',appearance:'외형',outfit:'의상',expression:'표정',pose:'자세',gaze:'시선',prop:'소지품',action:'행동'};
export type Term={text:string;weight:number;origin:'user'|'preset'|'reference'|'model';kind:'tag'|'natural_language'|'user_literal';tag_ref:string|null};
export type Character={id:string;label:string;identity_tag_id:number|null;copyright_tag_ids:number[];nai_subject:'girl'|'boy'|'other'|null;fields:Record<Group,string>;locked_groups:Group[];required_terms:Term[];undesired_terms:Term[];position:{x:number;y:number}|null};
export type Relation={id:string;participant_ids:string[];actor_id:string|null;target_ids:string[];direction:'directed'|'mutual'|'group';action_ko:string;details_ko:string;locked:boolean};
export type IR={schema_version:'1.1';characters:{id:string;groups:Record<Group,Term[]>;undesired:Term[];notes_ko:string[]}[];relations:{id:string;participant_ids:string[];actor_id:string|null;target_ids:string[];direction:'directed'|'mutual'|'group';action_tag:string|null;action_tag_ref:string|null;character_clauses:{character_id:string;text_en:string}[]}[];shared_terms:Term[];unresolved:{code:string;character_ids:string[];message_ko:string}[]};
export type Input={project_revision:number;task:'generate'|'rewrite'|'shorten'|'vary';request_ko:string;rating:'SFW'|'NSFW';nai_profile_id:string;characters:Character[];relations:Relation[];controls:{format:'tags'|'hybrid';detail:'short'|'standard'|'detailed';expansion:'none'|'minimal'|'creative';output_scope:'characters_only'|'characters_with_shared_fragment';variant_count:number;editable_character_ids:string[];editable_groups:Group[];external_base_reserved_tokens:number|null};previous_ir:IR|null};
export type Rendered={characters:{id:string;label:string;prompt:string;uc:string;terms:Term[];notes_ko:string[]}[];shared_fragment:string|null;count_status:string;placement:{character_id:string;label:string;instruction:string}[];scope_notice:string|null};
export type Candidate={id:string;ir:IR;rendered:Rendered;tag_evidence:Record<string,any>[];budget:Record<string,any>;mode:string;validation_status:string;warnings:{message_ko:string}[];[key:string]:any};
export type Project={schema_version:'1.1';id:string;name:string;revision:number;input:Input;candidates:Candidate[];manual_overrides:Record<string,string>;settings:Record<string,any>;history:Record<string,any>[];tag_db_snapshot:Record<string,any>|null;legacy:Record<string,any>};
export type Profiles=Record<string,{label:string;max_characters:number;negative_weight:boolean;position_adapter:string}>;
export const term=(text:string):Term=>({text,weight:1,origin:'user',kind:'tag',tag_ref:null});
export function newInput(characters:Character[]):Input{return {project_revision:0,task:'generate',request_ko:'',rating:'NSFW',nai_profile_id:'nai-v5-full',characters,relations:[],controls:{format:'hybrid',detail:'standard',expansion:'minimal',output_scope:'characters_with_shared_fragment',variant_count:1,editable_character_ids:[],editable_groups:[...groups],external_base_reserved_tokens:128},previous_ir:null}}
